updated go test timeout to 20m

diff --git a/.github/workflows/terratest-integration.yaml b/.github/workflows/terratest-integration.yaml
--- a/.github/workflows/terratest-integration.yaml
+++ b/.github/workflows/terratest-integration.yaml
@@ -49,7 +49,7 @@ jobs:
 
       - name: Run Terratest on ASG and ALB
         working-directory: tests/integration/alb_asg
-        run: go test -v || true  # prevent fail from stopping destroy
+        run: go test -v -timeout 20m || true  # prevent fail from stopping destroy
 
       - name: Cleanup - Terraform Destroy
         if: always()
