updated workflow with terraform destroy safety net

diff --git a/.github/workflows/terratest-integration.yaml b/.github/workflows/terratest-integration.yaml
--- a/.github/workflows/terratest-integration.yaml
+++ b/.github/workflows/terratest-integration.yaml
@@ -49,7 +49,12 @@ jobs:
 
       - name: Run Terratest on ASG and ALB
         working-directory: tests/integration/alb_asg
-        run: go test -v
+        run: go test -v || true  # prevent fail from stopping destroy
+
+      - name: Cleanup - Terraform Destroy
+        if: always()
+        working-directory: tests/integration/alb_asg
+        run: terraform destroy -auto-approve
 
   promote-to-stage:
     name: Promote test to stage
diff --git a/.github/workflows/unit-tests.yaml b/.github/workflows/unit-tests.yaml
--- a/.github/workflows/unit-tests.yaml
+++ b/.github/workflows/unit-tests.yaml
@@ -51,7 +51,12 @@ jobs:
 
       - name: Run Terratest for ${{ matrix.module }}
         working-directory: tests/unit/${{ matrix.module }}
-        run: go test -v
+        run: go test -v || true  # Let destroy run even if test fails
+
+      - name: Terraform Destroy (always)
+        if: always()
+        working-directory: tests/unit/${{ matrix.module }}
+        run: terraform destroy -auto-approve
 
   promote-to-test:
     name: Promote dev to test
